name: liebe_app
description: "Liebe AI - Your Professional AI Assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  permission_handler: ^11.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#00051a"
  adaptive_icon_foreground: "assets/logo/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
